name: Flutter CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install and set Flutter version
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version

    - name: Clean the project
      run: flutter clean
    - name: Get all packages
      run: flutter pub get

    # [Unit Test] Repositories
    - name: Unit test on Auth Repository
      working-directory: ./packages/repositories/auth_repository
      run: flutter test --coverage