name: Flutter CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
  
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install and set Flutter version
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Restore packages
      run: flutter pub get
    - name: Check formatting issue
      run: flutter format --set-exit-if-changed .
    - name: Analyze
      run: flutter analyze .

    # [UT] Repositories
    - name: Unit Test on Auth Repository
      working-directory: ./packages/repositories/auth_repository
      run: flutter test --coverage